name: Agent kill test

on:
  workflow_dispatch:

jobs:
  latest:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit

      - uses: prateek-stepsecurity/harden-runner@a69703feefe5b03ed8c0cd8148b0eef9cb347dff # int
        with:
          egress-policy: audit
          
      - uses: actions/checkout@f548e57e544e1ff5a4c46bf1e1b8685f8e4a348a # main

      - name: do curl calls
        if: always()
        run: |
          curl -v -4 google.com
          curl -v -4 youtube.com
          curl -v -4 microsoft.com
          curl -v -4 bing.com
          
      - name: stop agent 
        run: |
         set -x
         doWork(){
           systemctl --version
           pidof agent || true
           sudo strace -f systemctl stop agent.service || true
           pidof agent || true
         }
         doWork || true
      - name: print agent logs
        if: always()
        run: sudo cat /home/agent/agent.log
        