name: Agent kill test

on:
  workflow_dispatch:

jobs:
  latest:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c # v2.21.0
        with:
          egress-policy: audit

      - uses: prateek-stepsecurity/harden-runner@d867105c9eeb1add8fb44cd8574129594c68cc17 # int
        with:
          egress-policy: audit
          
      - uses: actions/checkout@main

      - name: do curl calls
        if: always()
        run: |
          curl -v -4 google.com
          curl -v -4 youtube.com
          curl -v -4 microsoft.com
          curl -v -4 bing.com
          
      - name: stop agent 
        run: |
         set -x
         doWork(){
           systemctl --version
           pidof agent || true
           sudo strace -f systemctl stop agent.service || true
           pidof agent || true
         }
         doWork || true
      - name: print agent logs
        if: always()
        run: sudo cat /home/agent/agent.log
        