name: CI
on:
  workflow_dispatch:
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: node:18
      env:
        NODE_ENV: development
      options: --cpus 1
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@351661ca32ac09a36dc5ee2d536e3128f2a3c8ed # v2.22.0
        with:
          egress-policy: audit

      - name: Check dockerenv with sudo
        run: sudo ls /.dockerenv || echo No dockerenv
