name: Enum

on:
  workflow_dispatch:

jobs:
  enum:
    if: always()
    runs-on: ARMLinuxRunner
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
        with:
          egress-policy: audit

      - name: lsm param
        run: cat /sys/kernel/security/lsm

      - run: cat /boot/config-`uname -r` | grep CONFIG_BPF_KPROBE_OVERRIDE

      - run: ls -lah /
