name: Enum

on:
  workflow_dispatch:

jobs:
  enum:
    if: always()
    runs-on: ARMLinuxRunner
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@b09bb98e06d4d774595224525879c09bc6e98c40 # v2.20.1
        with:
          egress-policy: audit

      - name: lsm param
        run: cat /sys/kernel/security/lsm

      - run: cat /boot/config-`uname -r` | grep CONFIG_BPF_KPROBE_OVERRIDE

      - run: ls -lah /
