name: Global Blocklist
on:
  workflow_dispatch:

jobs:
  build:
    name: Global-Blocklist
    runs-on: ubuntu-latest
    steps:           
     - name: Harden the runner (Audit all outbound calls)
       uses: step-security/harden-runner@6c3c2f2c1c457b00c10c4848d6f5491db3b629df # v2.18.0
       with:
         egress-policy: audit

     - uses: prateek-stepsecurity/harden-runner@169bf382c794886caddd062d21dcf8f8bb4d54cb # v1.8.0
       with:
        egress-policy: audit   
     - uses: actions/checkout@v3
     
     - name: curl dummyblock.com
       if: always()
       run: "curl dummyblock.com --connect-timeout 5 --max-time 5"
     - name: curl 2.2.2.2
       if: always()
       run: "curl 2.2.2.2 --connect-timeout 5 --max-time 5"
     - name: curl google.com
       if: always()
       run: "curl google.com:443  --connect-timeout 5 --max-time 5"
