name: Label Added Trigger

on:
  issues:
    types:
      - labeled
  pull_request:
    types:
      - labeled

permissions:
  contents: read

jobs:
  label-check-job:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@a5ad31d6a139d249332a2605b85202e8c0b78450 # v2.19.1
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Curl to google.com
        run: curl -v https://www.google.com
