name: Policy Store - Repo Level

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  repo-level-policy:
    runs-on: ubuntu-latest

    steps:
      - name: Harden the runner
        uses: step-security/harden-runner@74e0b3a07e0fbb577c4d31bcfd72e414699cae1a # feature/policy-store
        with:
          use-policy-store: true
          api-key: ${{ secrets.STEP_SECURITY_API_KEY }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: call google
        run: |
          curl https://google.com

      - name: call bing
        run: |
          curl https://bing.com

      - name: call microsoft
        run: |
          curl https://microsoft.com

      - name: call amazon
        run: |
          curl https://amazon.com
