name: Policy Store - Reusable Caller (arm-int-tests)

on:
  workflow_dispatch:

jobs:
  call-reusable:
    uses: step-integration-tests/arm-int-tests/.github/workflows/policy-store-reusable.yml@main
    secrets:
      STEP_SECURITY_API_KEY: ${{ secrets.STEP_SECURITY_API_KEY }}
