name: Policy Store - Repo Level

on:
  workflow_dispatch:

jobs:
  repo-level-policy:
    runs-on: ubuntu-latest

    steps:
      - name: Harden the runner
        uses: step-security/harden-runner@289f73efeab9e206926c0a2520f64f2a6b9b9b69 # feature/policy-store
        with:
          use-policy-store: true
          api-key: ${{ secrets.STEP_SECURITY_API_KEY }}

      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: call google
        run: |
          curl https://google.com

      - name: call bing
        run: |
          curl https://bing.com

      - name: call microsoft
        run: |
          curl https://microsoft.com

      - name: call amazon
        run: |
          curl https://amazon.com
