name: PS Pattern Wildcard Cross Repo

on:
  workflow_dispatch:

jobs:
  ps-pattern-wildcard-cross-repo:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: step-security/harden-runner@rc
        with:
          use-policy-store: true
          api-key: ${{ secrets.STEP_SECURITY_API_KEY }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: do stepsecurity.io
        if: always()
        run: curl https://stepsecurity.io  --connect-timeout 5

      - name: do google.com
        if: always()
        run: curl https://google.com  --connect-timeout 5
