name: Test Fail with Compromised Action

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test-fail:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@b09bb98e06d4d774595224525879c09bc6e98c40 # v2.20.1
        with:
          egress-policy: audit

      - name: sleep
        run: |
          echo "Sleep 5"
          sleep 5


      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use compromised action (should be blocked)
        uses: step-security/dummy-compromised-action@c96c327cecdb71e8f031080ba8ad208feb25b13d # v1
        
      - name: sleep
        if: always()
        run: |
          echo "Sleep 5"
          sleep 5

      - name: Display results
        run: |
          echo "Workflow completed successfully"
          echo "This is a fail scenario for workflow run policies"
