name: azure/setup-kubectl
on:
  workflow_dispatch:
  
permissions:
  contents: read

jobs:
  generate-jobs:
    name: Generate Jobs
    runs-on: ubuntu-latest
   
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
        with:
          egress-policy: audit

      - uses: azure/setup-kubectl@0c5e050edfed71b2b50731ab044d42489d51c129 # vv4.0.0
      - run: sleep 300
        
           
